//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDemo01
{
    using System;
    using System.Collections.Generic;
    
    public partial class BCL_Goods
    {
        public System.Guid SysNo { get; set; }
        public string GoodsTitle { get; set; }
        public string ArticleNo { get; set; }
        public System.Guid UserSysNo { get; set; }
        public string SkuId { get; set; }
        public System.Guid CategorySysNo { get; set; }
        public double Weight { get; set; }
        public string Fabric { get; set; }
        public string Style { get; set; }
        public string Size { get; set; }
        public string Color { get; set; }
        public string Format { get; set; }
        public string Dimension { get; set; }
        public decimal ClearAmount { get; set; }
        public decimal PackageAmount { get; set; }
        public decimal MarginAmount { get; set; }
        public decimal OutAmount { get; set; }
        public decimal SendAmount { get; set; }
        public string BarCode { get; set; }
        public System.Guid SetsLableSysNo { get; set; }
        public System.DateTime LastDate { get; set; }
        public decimal ServiceAmount { get; set; }
        public System.Guid BrandSysNo { get; set; }
        public string Long { get; set; }
        public string Width { get; set; }
        public string Height { get; set; }
        public string Remark { get; set; }
        public string ExtendValue { get; set; }
    }
}
